# -*- coding: utf-8 -*-
"""lyrics_identifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbYEp0nY9_ELeot34CSXnxLGkxDZLBc9
"""

import pandas as pd
import numpy as np
import re
import nltk

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('stopwords')
from nltk.corpus import stopwords

df = pd.read_csv("/content/Spotify Million Song Dataset_exported.csv")
df.head()

df.columns

df = df[['artist', 'song', 'text']]
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

df.head()

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)  # remove punctuation/numbers
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    return " ".join(tokens)

df['clean_text'] = df['text'].apply(clean_text)
df[['artist', 'song', 'clean_text']].head()

def remove_title_leakage(row):
    lyrics = row['clean_text']
    title_words = row['song'].lower().split()

    for word in title_words:
        lyrics = lyrics.replace(word, '')

    return lyrics

df['clean_text'] = df.apply(remove_title_leakage, axis=1)

vectorizer = TfidfVectorizer(
    analyzer='char',
    ngram_range=(3, 5),
    max_features=8000
)

tfidf_matrix = vectorizer.fit_transform(df['clean_text'])

def identify_song(snippet):
    snippet = clean_text(snippet)
    snippet_vector = vectorizer.transform([snippet])

    similarity_scores = cosine_similarity(snippet_vector, tfidf_matrix)[0]
    best_match_index = similarity_scores.argmax()

    return {
        "Song Title": df.iloc[best_match_index]['song'],
        "Artist": df.iloc[best_match_index]['artist'],
        "Confidence Score": round(similarity_scores[best_match_index], 3)
    }

identify_song("i love you")

def identify_song_top_k(snippet, k=5):
    snippet = clean_text(snippet)
    snippet_vector = vectorizer.transform([snippet])

    similarity_scores = cosine_similarity(snippet_vector, tfidf_matrix)[0]
    top_k_indices = similarity_scores.argsort()[-k:][::-1]

    predictions = []
    for idx in top_k_indices:
        predictions.append({
            "song": df.iloc[idx]['song'],
            "artist": df.iloc[idx]['artist'],
            "score": similarity_scores[idx]
        })
    return predictions

def generate_snippet(text, length=120):
    return text[:length]

def top_k_accuracy(k=5, samples=100):
    correct = 0
    test_data = df.sample(samples, random_state=42)

    for _, row in test_data.iterrows():
        snippet = generate_snippet(row['clean_text'])
        predictions = identify_song_top_k(snippet, k)

        predicted_songs = [p['song'] for p in predictions]

        if row['song'] in predicted_songs:
            correct += 1

    return correct / samples

print("Top-1 Accuracy:", top_k_accuracy(k=1))
print("Top-3 Accuracy:", top_k_accuracy(k=3))
print("Top-5 Accuracy:", top_k_accuracy(k=5))